version: "1.1"

services:
  postgres:
    image: postgres 
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: review
      POSTGRES_PASSWORD: password

  node_code:
    image: dinesh050/docker-1
    ports:
      - "8002:8000"
    
      
